version: "3.9"

services:
  backend:
    build:
      context: https://github.com/AdamBassoumi/Sequence_Gen.git
      dockerfile: app/Dockerfile
    container_name: sequence_gen_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: https://github.com/AdamBassoumi/Sequence_Gen.git#main:frontend
      dockerfile: Dockerfile
    container_name: sequence_gen_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
